### ISSUE TITLE
About the evaluation metrics

### ISSUE THREAD

**Issue by YiYang-SCUT** [ldzhangyx/MusicMagus#11]
Could you please share the code you used to calculate the evaluation metrics in your objective and subjective experiments? I would appreciate it if you did! 
Another question is, in your objective experiment, let's say the timbre transfer task, of the 60 music files you generated, is the corresponding timbre in the prompt only piano/viola? And is the corresponding genre only jazz or country? Can it be any other choice? Could you tell me the range of choices for genre and timbre in the prompt? I would appreciate it if you did!

**Comment by ldzhangyx** [comment]
The 60 files are randomly generated. You may find more information in my phd thesis: https://arxiv.org/pdf/2411.12641, where this version I updated some details for MusicMagus. 

The principle I choose these pairs is mainly because TransPlayer only supports limited instruments and it is for a fair comparison.

I did not really save the evaluation script. But They are very easy to be implemented with:

https://github.com/LAION-AI/CLAP
https://github.com/gudgud96/frechet-audio-distance
https://librosa.org/doc/0.8.1/index.html
